version: '2'
services:
  config-server:
    image: config-server
    ports:
     - "8888:8888"
  servicediscovery:
    image: servicediscovery
    depends_on:
     - config-server
    ports:
     - "8761:8761"
  apigateway:
    image: apigateway
    depends_on:
     - eureka-server
    ports:
     - "8080:8080"